esphome:
  name: $device_name
  friendly_name: $device_friendly_name

# Enable logging
logger:

# Enable Home Assistant API
api:

#Conveniently, the PW will happily upload to a non-pw device, at which point it'll be set
ota:
  password: "SomeRandomPassword" #TBH I'm not 100% this actually works correctly...

# I don't believe this is actually required for the uptime sensor, but at least the timestamps will be logical
time:
  - platform: homeassistant
    id: homeassistant_time

# Now with the Homeassistant 'Diagnostic' sensors, we can just bake these into everything! (without cluttering the HA UI)
sensor:
  - platform: uptime
    name: "Uptime"
    
web_server: # Note: this feature apparently eats a lot of flash space & ram, but I really don't find even my most 'busy' '8266s struggling
  port: 80
  
button: # Honestly, these are just convenient to have for troubleshooting
  - platform: safe_mode
    name: "Reboot into Safe Mode"
  - platform: restart
    name: "Reboot"
  - platform: factory_reset
    name: "Factory reset"